// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

extern char currentGroup;
extern bool isLooping;

void onKedarnathPressed(lv_event_t *e) {
  currentGroup = 'a';  // Set folder "a"
  isLooping = true;
  printf("%c\n", currentGroup);  // Correct way to print a char
}

void onRishikeshPressed(lv_event_t *e) {
  currentGroup = 'b';  // Set folder "b"
  isLooping = true;
  printf("%c\n", currentGroup);  // Correct way to print a char
}

void onHomePressed(lv_event_t *e) {
  currentGroup = 'c';  // Set folder "c"
  isLooping = true;
  printf("%c\n", currentGroup);  // Correct way to print a char
}

void onFourPeoplePressed(lv_event_t *e) {
  currentGroup = 'd';  // Set folder "d"
  isLooping = true;
  printf("%c\n", currentGroup);  // Correct way to print a char
}

void onFamilyPressed(lv_event_t *e) {
  currentGroup = 'e';  // Set folder "e"
  isLooping = true;
  printf("%c\n", currentGroup);  // Correct way to print a char
}

void onOtherFriendsPressed(lv_event_t *e) {
  currentGroup = 'f';  // Set folder "f"
  isLooping = true;
  printf("%c\n", currentGroup);  // Correct way to print a char
}
