// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: new_proj

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void onKedarnathPressed(lv_event_t * e);
void onFamilyPressed(lv_event_t * e);
void onFourPeoplePressed(lv_event_t * e);
void onRishikeshPressed(lv_event_t * e);
void onHomePressed(lv_event_t * e);
void onOtherFriendsPressed(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
